# This is a basic workflow to help you get started with Actions

name: challenge
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  job1:
    name: First job
    runs-on: windows-latest
    run: echo this is job 1!
  job2:
    name: Second job
    runs-on: ubuntu-latest
    run: echo this is job 2!
  job3:
    name: Third job
    runs-on: macos-latest
    run: echo this is job 3!
  job4:
    needs: [job1, job2, job3]
    name: Fourth job
    runs-on: macos-latest
    run: echo this is job 4!
